### ISSUE TITLE
Modify the SignUp/Login page Ui for the Frontend

### ISSUE THREAD

**Issue by SumitKumar-17** [algovengers/Hairify#48] opened 2024-05-10 17:46 UTC
Hi I want to work on this issue. Can you assign this issue to me under GSSoc'24?
I will make a new and responsive sign up/login Ui for the frontend part of the application

**Comment by afeefuddin** [comment] 2024-05-10 17:54
Sure assigned.

**Comment by SumitKumar-17** [comment] 2024-05-10 17:57
Thanks I will start working on it

**Comment by SumitKumar-17** [comment] 2024-05-10 18:32
@afeefuddin I have completed the feature and open a PR for it . Please have a look on it .

**Comment by Tanishasi** [comment] 2024-05-15 14:33
Hello, if the issue is up for modifying the signup and login then please assign it to me, I would like to work on it. Thank You!

**Comment by SumitKumar-17** [comment] 2024-05-15 15:21
@afeefuddin sure I will complete it by today

**Comment by afeefuddin** [comment] 2024-05-16 20:20
Completed in #73

**Closed by afeefuddin** 2024-05-16 20:20 UTC
Labels: enhancement, gssoc, Level 2
