### ISSUE TITLE
Fixing signup page

### ISSUE THREAD

**Issue by shreyasadhasivam** [algovengers/Hairify#101] opened 2024-05-14 20:12 UTC
GsSOC '24 contributor
I would like to add javascript constraints to the email id and also add required fields and give appropiate response. Please assign this issue to me

**Comment by Tanishasi** [comment] 2024-05-15 14:31
Hi, if the issue is open then please assign it to me, I would like to work on it.

**Comment by afeefuddin** [comment] 2024-06-02 08:44
Please keep the issue title more clear, as of now this is duplicate with the issue #129 (which was created later but got more attention due to a better issue title)

**Closed by afeefuddin** 2024-06-02 08:44 UTC
